import { useState } from "react";
// import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";
import axios from "axios";

import styles from "../../styles/Home.module.css";

export default function Home() {
  const [userEmail, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const userEmailHandler = (e) => {
    setEmail(e.target.value);
  };

  const passwordHandler = (e) => {
    setPassword(e.target.value);
  };

  const buttonHandler = (e) => {
    e.preventDefault();
    if (userEmail.trim() === "" || password.trim() === "") {
      return console.log("Enter values!!!");
    } else {
      console.log(userEmail.trim());
      console.log(password.trim());
    }

    async function loginButtonFunc() {
      try {
        const res = await axios.post(
          "http://localhost:3000/api/requests/login",
          {
            email: userEmail,
            password,
          }
        );
        console.log(res, "Successfully loggin in! (Frontend)");
      } catch (e) {
        console.log(e, "Error! (Frontend)");
      }
    }

    loginButtonFunc();
  };

  return (
    <div className={styles.mainContainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.mainNav}>
        <Link href="/">
          <a className={styles.navText}>Home</a>
        </Link>
        <Link href="/signup">
          <a className={styles.navText}>Sign up</a>
        </Link>
      </div>

      <main>
        <form onSubmit={buttonHandler} className={styles.subContainer}>
          <input
            type="email"
            placeholder="Email"
            className={styles.loginUserInput}
            onChange={userEmailHandler}
            value={userEmail}
          />
          <input
            type="password"
            placeholder="Password"
            className={styles.loginUserInput}
            onChange={passwordHandler}
            value={password}
          />
          <div>
            <button className={styles.button}>Log in</button>
          </div>
        </form>
      </main>
    </div>
  );
}

//   try {
//     const res = await axios.post(
//       "http://localhost:3000/api/requests/login",
//       {
//         email: userEmail,
//         password,
//       }
//     );
//     console.log(res, "Successfully loggin in! (Frontend)");
//   } catch (e) {
//     console.log(e, "Error! (Frontend)");
//   }

// await axios("http://localhost:3000/api/requests/login", {
//   method: "POST",
//   headers: {
//     "Content-Type": "application/json",
//   },
//   data: {
//     email: userEmail,
//     password,
//   },
// })
//   .then((res) => {
//     console.log(res, "Successfully loggin in! (Frontend)");
//   })
//   .catch((e) => {
//     console.log(e, "Error! (Frontend)");
//   });
